# Read the ”datacloud.csv” file. It contains the observation of the datapoints generated by 3 independent 2d random laws
datacloud_address = "~/visualisation-donnees/R-pratice/dataCloud.csv"
datacloud <- read.csv(datacloud_address, header = TRUE, sep = ",", stringsAsFactors = FALSE)
clusters <- unique(datacloud$cluster)

# Assume the data is in a data frame called df
set.seed(123)  # Set seed for reproducible results

# Apply k-means to find 3 clusters using the columns x and y
kmeans_result <- kmeans(datacloud[, c("x", "y")], centers = 3)

# Display the discovered cluster centers
print(kmeans_result$centers)

# Add the discovered clusters to the original data frame
datacloud$predicted_cluster <- kmeans_result$cluster

# View the first rows with the assigned clusters
head(datacloud)

library(ggplot2)

ggplot(datacloud, aes(x = x, y = y, color = factor(predicted_cluster))) +
  geom_point(size = 1) +  # Puntos para los datos
  geom_point(data = as.data.frame(kmeans_result$centers), 
             aes(x = x, y = y), color = "black", size = 2, shape = 4) +  # Centros
  labs(title = "K-means Clustering", color = "Cluster") 

# 3 - Air Quality in Toulouse
# Each dataset is named as follows: AEROSOL_NUMEROSERIE_STATION.csv
# First column defines a useless line number
# Second column represents the measure date, expressed as the number of seconds ellapsed since 1970 (aka unix timestamp).
# Last column contains the measured concentration concentration (in g.m3)

# 3.1 Import the data
# Establecer el directorio donde están los archivos CSV
airdirectory <- "~/visualisation-donnees/R-pratice/dataset"

# Obtener una lista de todos los archivos CSV en la carpeta
files_csv <- list.files(path = airdirectory, pattern = "\\.csv$", full.names = TRUE)

# Leer todos los archivos CSV en una lista
datasets <- lapply(files_csv, function(file) {
  read.csv(file, header = TRUE, sep = ",", stringsAsFactors = FALSE)
})

# Asignar nombres a los datasets (opcional, usando los nombres de los archivos)
names(datasets) <- basename(archivos_csv)

# Verificar las primeras filas del primer dataset
head(datasets[[1]])
